#!/bin/sh
set -eu
while read -r local_ref local_oid remote_ref remote_oid; do
  case "$local_oid" in 0000000000000000000000000000000000000000) continue ;; esac
  "$(git rev-parse --show-toplevel)/.githooks/privacy-check" --history "$local_oid"
done
