apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegis
resources:
  - namespace.yaml
  - secret.yaml
  - storage.yaml
  - backend.yaml
  - frontend.yaml
  - observability.yaml
  - ingress.yaml
configMapGenerator:
  - name: grafana-datasource
    files:
      - prometheus.yml=../grafana/provisioning/datasources/prometheus.yml
  - name: grafana-dashboard-provider
    files:
      - aegis.yml=../grafana/provisioning/dashboards/aegis.yml
  - name: grafana-dashboard
    files:
      - aegis-overview.json=../grafana/dashboards/aegis-overview.json
