apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liims-data
  namespace: liims
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: liims
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: liims
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
